name: CI

on:
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - uses: sbt/setup-sbt@6444f4c8111de4b9059c3975def104b03cfaa5f0 # v1.5.2

      - name: Run SBT tasks
        run: >
          sbt
          scalafmtCheckAll
          scalafmtSbtCheck
          test
